os: linux

dist: trusty

language: python

python:
  - "3.6"

addons:
  sonarcloud:
    organization: "pagesage"
    token: $SONAR_TOKEN

script:
  - sonar-scanner
  - pip install --upgrade pip
  - pip install -r ./requirements/test.txt
  - pytest --cov=./

after_success:
  - codecov
